-- MySQL Script generated by MySQL Workbench
-- Sat Jun 20 13:58:44 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema seminario_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema seminario_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seminario_db` DEFAULT CHARACTER SET utf8 ;
USE `seminario_db` ;

-- -----------------------------------------------------
-- Table `seminario_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seminario_db`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seminario_db`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seminario_db`.`categorias` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seminario_db`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seminario_db`.`posts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `contenido` TEXT NOT NULL,
  `users_id` INT(11) NOT NULL,
  `categorias_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_posts_categorias1_idx` (`categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `seminario_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `seminario_db`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
